# Generated by Django 2.1.5 on 2019-02-11 08:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField()),
                ('upload', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Yuklemeler', verbose_name='PDF yuklemeler')),
            ],
        ),
    ]
