# Generated by Django 2.1.5 on 2019-02-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_statistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='upload',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
